--- #YAML:1.0
name: CGI-Wiki-Plugin-RSS-Reader
version: 1.2
license: perl
distribution_type: module
requires:
  LWP::Simple: 0
  XML::RSS: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  CGI::Wiki::Plugin::RSS::Reader:
    file: lib/CGI/Wiki/Plugin/RSS/Reader.pm
    version: 1.2
generated_by: Module::Build version 0.21
